// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { CLICommandOption, CLICommandArgument } from "@microsoft/teamsfx-api";

export const AddKnowledgeOptions: CLICommandOption[] = [
  {
    name: "knowledge-source",
    type: "string",
    description: "Knowledge source.",
    required: true,
    default: "web-search",
    choices: ["web-search", "oneDrive-sharePoint", "embedded-knowledge"],
  },
];
export const AddKnowledgeArguments: CLICommandArgument[] = [];
