# This is just an example workflow for continuous deployment.
# You should customize it to meet your own requirements.
name: 'Continuous Deployment'
on:
  # When new commits are pushed onto the main branch.
  push:
    branches:
      - main
jobs:
  buildAndPublish:
    runs-on: ubuntu-latest
    # You can uncomment the line below to use environments (refer to https://docs.github.com/en/actions/reference/environments). 
    #environment: test_environment
    env:
      AZURE_ACCOUNT_NAME: ${{secrets.AZURE_ACCOUNT_NAME}}
      AZURE_ACCOUNT_PASSWORD: ${{secrets.AZURE_ACCOUNT_PASSWORD}}
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      M365_ACCOUNT_NAME: ${{secrets.M365_ACCOUNT_NAME}}
      M365_ACCOUNT_PASSWORD: ${{secrets.M365_ACCOUNT_PASSWORD}}

      # The following line is to enable insider preview features.
      TEAMSFX_INSIDER_PREVIEW: true
      # To specify the env name for multi-env feature.
      TEAMSFX_ENV_NAME: staging

    steps:
      # Setup environment.
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Checkout the code
        uses: actions/checkout@v2
        
      # Build the project.
      # The way to build the current project depends on how you scaffold it.
      # Different folder structures require different commands set.
      # 'npm ci' is used here to install dependencies and it depends on package-lock.json.
      # If you prefer to use 'npm ci', please make sure to commit package-lock.json first, or just change it to 'npm install'.
      - name: Build the project
        run: cd tabs && npm ci && npm run build && cd -

      # Run unit test.
      # Currently, no opinionated solution for unit test provided during scaffolding, so,
      # set up any unit test framework you prefer (for example, mocha or jest) and update the commands accordingly in below.
      - name: Run Unit Test
        run: cd tabs && npm run test && cd -

      # We suggest to do the `teamsfx provision` step manually or in a separate workflow. The following steps are for your reference.
      # After provisioning, you should commit necessary files under .fx into the repository.
      # You should copy content of .fx/states/${TEAMSFX_ENV_NAME}.userdata, and save it in the repository secrets (https://docs.github.com/en/actions/reference/encrypted-secrets) which can be refered by the step with name 'Generate userdata'. 
      #- name: Provision hosting environment
      #  uses: OfficeDev/teamsfx-cli-action@v1
      #  env:
      #    TEAMSFX_BICEP_ENV_CHECKER_ENABLE: true
      #  with:
      #    commands: provision
      #    subscription: ${{env.AZURE_SUBSCRIPTION_ID}}
      #    env: ${{env.TEAMSFX_ENV_NAME}}

      #- name: Commit provision configs if necessary
      #  uses: stefanzweifel/git-auto-commit-action@v4
      #  with:
      #    commit_message: "chore: commit provision configs"
      #    file_pattern: .fx/*
      
      #- name: Upload userdata as artifact
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: defaultUserData
      #    path: .fx/states/${{env.TEAMSFX_ENV_NAME}}.userdata
      
      - name: Generate userdata
        env:
          USERDATA_CONTENT: ${{ secrets.USERDATA_CONTENT }}
        run: |
          [ ! -z "${USERDATA_CONTENT}" ] && echo "${USERDATA_CONTENT}" > .fx/states/${TEAMSFX_ENV_NAME}.userdata
        
      - name: Deploy to hosting environment
        uses: OfficeDev/teamsfx-cli-action@v1
        with:
          commands: deploy
          env: ${{env.TEAMSFX_ENV_NAME}}

      # This step is to pack the Teams App as zip file,
      # which can be used to be uploaded onto Teams Client for installation.
      - name: Package Teams App for publishing
        uses: OfficeDev/teamsfx-cli-action@v1
        with:
          commands: package
          env: ${{env.TEAMSFX_ENV_NAME}}

      - name: Upload Teams App's package as artifact
        uses: actions/upload-artifact@v2
        with:
          name: appPackage
          path: appPackage/appPackage.${{env.TEAMSFX_ENV_NAME}}.zip

      - name: Publish Teams App
        uses: OfficeDev/teamsfx-cli-action@v1
        with:
          commands: publish
          env: ${{env.TEAMSFX_ENV_NAME}}
